item {
    name: "0",
    id: 1,
    display_name: "0"
}
item {
    name: "1",
    id: 2,
    display_name: "1"
}
item {
    name: "2",
    id: 3,
    display_name: "2"
}
item {
    name: "3",
    id: 4,
    display_name: "3"
}
item {
    name: "Chairs",
    id: 5,
    display_name: "Chairs"
}
item {
    name: "Doors",
    id: 6,
    display_name: "Doors"
}
item {
    name: "Garments",
    id: 7,
    display_name: "Garments"
}
item {
    name: "Wires",
    id: 8,
    display_name: "Wires"
}
item {
    name: "chair",
    id: 9,
    display_name: "chair"
}
item {
    name: "chairs",
    id: 10,
    display_name: "chairs"
}
item {
    name: "doors",
    id: 11,
    display_name: "doors"
}
item {
    name: "garments",
    id: 12,
    display_name: "garments"
}
item {
    name: "wires",
    id: 13,
    display_name: "wires"
}
